(function(){"use strict";
var URL="https://vesjjckdwranojwkybff.supabase.co",KEY="sb_publishable_QwTMpuSLaOwxFcqup7jMUw_h6BvNW8w",status=document.getElementById("cloud-status"),email=document.getElementById("cloud-email"),login=document.getElementById("cloud-login"),upload=document.getElementById("cloud-upload"),restore=document.getElementById("cloud-restore"),remove=document.getElementById("cloud-delete"),logout=document.getElementById("cloud-logout"),client=null,user=null;
function message(text,kind){status.textContent=text;status.className="cloudstatus "+(kind||"");}
function busy(on){[login,upload,restore,remove,logout].forEach(function(b){b.disabled=on;});}
function relevantKey(k){return k==="survey_templates_v2"||k==="tc_zone_pref"||k==="tallyfield_traffic_lab_v1"||k.indexOf("survey_session_v2_")===0;}
function collect(){var values={};for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(relevantKey(k))values[k]=localStorage.getItem(k);}return{format:"tallyfield-cloud-backup-v1",exported_at:new Date().toISOString(),values:values};}
function controls(){var signed=!!user;email.hidden=signed;login.hidden=signed;upload.hidden=!signed;restore.hidden=!signed;remove.hidden=!signed;logout.hidden=!signed;if(signed)message("Cloud ready · "+user.email,"ready");else message("Local mode · พร้อมใช้งานออฟไลน์","");}
async function init(){if(!window.supabase){message("Local mode · Cloud library unavailable","pending");return;}client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});var result=await client.auth.getSession();user=result.data.session&&result.data.session.user;controls();client.auth.onAuthStateChange(function(_event,session){user=session&&session.user;controls();});}
login.addEventListener("click",async function(){var value=email.value.trim();if(!value||!value.includes("@")){message("กรอกอีเมลที่ถูกต้อง","pending");return;}busy(true);message("กำลังส่งลิงก์เข้าสู่ระบบ…","pending");var r=await client.auth.signInWithOtp({email:value,options:{emailRedirectTo:"https://poramat0hm1-hub.github.io/tally-counter/"}});busy(false);if(r.error)message("ส่งลิงก์ไม่สำเร็จ: "+r.error.message,"pending");else message("ส่งลิงก์แล้ว · เปิดอีเมลบนอุปกรณ์นี้เพื่อเข้าสู่ระบบ","ready");});
upload.addEventListener("click",async function(){if(!user)return;busy(true);message("กำลังสำรองข้อมูล…","pending");var r=await client.from("survey_backups").upsert({user_id:user.id,name:"TallyField backup",payload:collect(),schema_version:1},{onConflict:"user_id"});busy(false);if(r.error)message("สำรองไม่สำเร็จ: "+r.error.message,"pending");else message("สำรองล่าสุดเมื่อ "+new Date().toLocaleString(),"ready");});
restore.addEventListener("click",async function(){if(!user)return;if(!confirm("กู้คืนข้อมูลจาก Cloud? ข้อมูล TallyField ในเครื่องนี้จะถูกแทนที่ และหน้าเว็บจะโหลดใหม่"))return;busy(true);message("กำลังกู้คืนข้อมูล…","pending");var r=await client.from("survey_backups").select("payload,updated_at").eq("user_id",user.id).maybeSingle();if(r.error||!r.data){busy(false);message(r.error?"กู้คืนไม่สำเร็จ: "+r.error.message:"ยังไม่มีข้อมูลสำรองบน Cloud","pending");return;}var payload=r.data.payload;if(!payload||payload.format!=="tallyfield-cloud-backup-v1"||!payload.values){busy(false);message("รูปแบบข้อมูลสำรองไม่ถูกต้อง","pending");return;}Object.keys(payload.values).forEach(function(k){if(relevantKey(k))localStorage.setItem(k,payload.values[k]);});location.reload();});
remove.addEventListener("click",async function(){if(!user||!confirm("ลบข้อมูลสำรองบน Cloud ของบัญชีนี้? ข้อมูลในอุปกรณ์จะไม่ถูกลบ และการลบนี้ย้อนกลับไม่ได้"))return;busy(true);var r=await client.from("survey_backups").delete().eq("user_id",user.id);busy(false);if(r.error)message("ลบไม่สำเร็จ: "+r.error.message,"pending");else message("ลบข้อมูลสำรองบน Cloud แล้ว · ข้อมูลในเครื่องยังอยู่","ready");});
logout.addEventListener("click",async function(){busy(true);await client.auth.signOut();busy(false);user=null;controls();});
init().catch(function(){message("Local mode · Cloud unavailable","pending");});
})();
